### PR TITLE
Feature/findbugs prop

### PR DESCRIPTION
**Pull request by dbmeneses**

### CODE REVIEW

**Comment by henryju** [comment]
Please rebase on master

**Comment by dbmeneses** [comment]
Done

**Comment by henryju** [comment]
The findbugs plugin may probably also be configured in <build> section of the pom (or plugin management). But that's fine for now to only consider <reporting>.

**Comment by dbmeneses** [comment]
The old implementation in sonar-findbugs was in fact only considering the
plugins section.

On 28 August 2015 at 17:25, Julien HENRY notifications@github.com wrote:

> Merged #2 https://github.com/mojohaus/sonar-maven-plugin/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mojohaus/sonar-maven-plugin/pull/2#event-395181739.

## 

_Duarte MENESES | *_SonarSource*
http://sonarsource.com

**Pull request merged**
